name: DeployApi   

env:
  # dotnet
  DOTNET_VERSION: 6.0.x
  
  # deploy
  PROJ_DIR: Inventory.Api # Api project directory
  
  SOURCE_DIR: publish # publish directory
  TARGET_DIR: workflow/api/publish # deploy directory in the remote machine
  
  SCRIPT_PATH: workflow/switchDeploy-api.sh # script file to deploy and switch api server
  
  # slack
  SLACK_AUTHOR: '' # hide author_name with empty string
  
on:
  push:
    branches:
      - main
    tags:
      - api-v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      
    - name: Publish Local
      run: dotnet publish ${{ env.PROJ_DIR }} -c Release -o ${{ env.SOURCE_DIR }}
      
    - name: Publish Remote
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "${{ env.SOURCE_DIR }}/*"
        target: ${{ env.TARGET_DIR }}
        rm: true
        strip_components: 1 # remove 1 level path of source directory
        
    - name: Deploy API
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: bash ${{ env.API_SCRIPT_PATH }}

    - name: Report
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: ${{ env.SLACK_AUTHOR }}
        fields: eventName,message,commit,author,ref,workflow,job,took,pullRequest
      env: 
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
      if: always() 
