name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-then-report:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Report
      uses: 8398a7/action-slack@v3
      with:
         status: custom
         custom_payload: |
          {
            text: "Custom Field Check",
            attachments: [{
              "author_name": "8398a7@action-slack", // json
              fallback: 'fallback',
              color: 'good',
              title: 'CI Result',
              text: 'Succeeded',
              fields: [{
                title: 'lower case',
                value: 'LOWER CASE CHECK'.toLowerCase(),
                short: true
              },
              {
                title: 'reverse',
                value: 'gnirts esrever'.split('').reverse().join(''),
                short: true
              },
              {
                title: 'long title1',
                value: 'long value1',
                short: false
              }],
              actions: [{
              }]
            }]
          }
      env: 
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
      if: always() 
