name: SlackBot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 'send' job
  send:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Send slack message
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author: madstone290@gmail.com
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
        if: always() 
          
